# Generated by Django 2.2.5 on 2019-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('distanceToArrival', models.IntegerField()),
                ('systemName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('systemName', models.TextField()),
                ('station_name', models.TextField()),
                ('sell_price', models.IntegerField()),
                ('max_landing_pad_size', models.TextField()),
                ('distance_to_star', models.IntegerField()),
            ],
        ),
    ]
